version: "3.9"
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    runtime: io.containerd.spin.v1
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - BackendBaseUrl=http://backend:80
      - AzureAd__ClientId=...
      - AzureAd__TenantId=...
      - AzureAd__ClientSecret=...
    ports:
      - "3000:80"
      - "3001:443"
    depends_on:
      - backend