FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ./shared/shared.csproj ./shared/
COPY ./frontend/frontend.csproj ./frontend/
RUN dotnet restore ./frontend/frontend.csproj

COPY ./shared/ ./shared/
COPY ./frontend/ ./frontend/
RUN dotnet publish ./frontend/frontend.csproj --no-restore -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
EXPOSE 80
ENV ASPNETCORE_URLS=http://+:80

WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "frontend.dll"]
