FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ./shared/shared.csproj ./shared/
COPY ./backend/Project.csproj ./backend/
RUN dotnet restore ./backend/Project.csproj

COPY ./shared/ ./shared/
COPY ./backend/ ./backend/
RUN dotnet publish ./backend/Project.csproj --no-restore -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
EXPOSE 80
ENV ASPNETCORE_URLS=http://+:80

WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "planner_exandimport_wasm.dll"]
