version: "3.9"
services:
  backend:
    image: tobiasfenster/planner-exandimport-wasm-backend:latest
    runtime: io.containerd.spin.v1
  frontend:
    image: tobiasfenster/planner-exandimport-wasm-frontend:latest
    environment:
      - BackendBaseUrl=http://backend:80
      - AzureAd__ClientId=...
      - AzureAd__TenantId=...
      - AzureAd__ClientSecret=...
    ports:
      - "3000:80"
      - "3001:443"
    depends_on:
      - backend