spin_version = "1"
authors = ["Tobias Fenster <tfenster@4psbau.de>"]
description = ""
name = "Planner-ExAndImport-Wasm"
version = "1.1.0"
trigger = { type = "http", base = "/" }

[[component]]
id = "planner_exandimport_wasm"
source = "/workspaces/planner-exandimport-wasm/backend/bin/Release/net7.0/planner_exandimport_wasm.wasm"
allowed_http_hosts = ["https://graph.microsoft.com"]
[component.build]
command = "dotnet build -c Release"
[component.trigger]
route = "/..."
